#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDNHD.Models.DataContexts
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HoaDonHaDong")]
	public partial class AdminDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNguoidung(Nguoidung instance);
    partial void UpdateNguoidung(Nguoidung instance);
    partial void DeleteNguoidung(Nguoidung instance);
    partial void InsertDangnhap(Dangnhap instance);
    partial void UpdateDangnhap(Dangnhap instance);
    partial void DeleteDangnhap(Dangnhap instance);
    #endregion
		
		public AdminDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HoaDonHaDongConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdminDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdminDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdminDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdminDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Nguoidung> Nguoidungs
		{
			get
			{
				return this.GetTable<Nguoidung>();
			}
		}
		
		public System.Data.Linq.Table<Dangnhap> Dangnhaps
		{
			get
			{
				return this.GetTable<Dangnhap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nguoidung")]
	public partial class Nguoidung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NguoidungID;
		
		private System.Nullable<int> _NhanvienID;
		
		private string _Taikhoan;
		
		private string _Matkhau;
		
		private System.Nullable<bool> _Isadmin;
		
		private EntitySet<Dangnhap> _Dangnhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNguoidungIDChanging(int value);
    partial void OnNguoidungIDChanged();
    partial void OnNhanvienIDChanging(System.Nullable<int> value);
    partial void OnNhanvienIDChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnIsadminChanging(System.Nullable<bool> value);
    partial void OnIsadminChanged();
    #endregion
		
		public Nguoidung()
		{
			this._Dangnhaps = new EntitySet<Dangnhap>(new Action<Dangnhap>(this.attach_Dangnhaps), new Action<Dangnhap>(this.detach_Dangnhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoidungID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NguoidungID
		{
			get
			{
				return this._NguoidungID;
			}
			set
			{
				if ((this._NguoidungID != value))
				{
					this.OnNguoidungIDChanging(value);
					this.SendPropertyChanging();
					this._NguoidungID = value;
					this.SendPropertyChanged("NguoidungID");
					this.OnNguoidungIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanvienID", DbType="Int")]
		public System.Nullable<int> NhanvienID
		{
			get
			{
				return this._NhanvienID;
			}
			set
			{
				if ((this._NhanvienID != value))
				{
					this.OnNhanvienIDChanging(value);
					this.SendPropertyChanging();
					this._NhanvienID = value;
					this.SendPropertyChanged("NhanvienID");
					this.OnNhanvienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="VarChar(30)")]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="VarChar(32)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isadmin", DbType="Bit")]
		public System.Nullable<bool> Isadmin
		{
			get
			{
				return this._Isadmin;
			}
			set
			{
				if ((this._Isadmin != value))
				{
					this.OnIsadminChanging(value);
					this.SendPropertyChanging();
					this._Isadmin = value;
					this.SendPropertyChanged("Isadmin");
					this.OnIsadminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nguoidung_Dangnhap", Storage="_Dangnhaps", ThisKey="NguoidungID", OtherKey="NguoidungID")]
		public EntitySet<Dangnhap> Dangnhaps
		{
			get
			{
				return this._Dangnhaps;
			}
			set
			{
				this._Dangnhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dangnhaps(Dangnhap entity)
		{
			this.SendPropertyChanging();
			entity.Nguoidung = this;
		}
		
		private void detach_Dangnhaps(Dangnhap entity)
		{
			this.SendPropertyChanging();
			entity.Nguoidung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dangnhap")]
	public partial class Dangnhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DangnhapID;
		
		private System.Nullable<int> _NguoidungID;
		
		private System.Nullable<int> _Solandangnhapsai;
		
		private System.Nullable<System.DateTime> _Thoigiandangnhap;
		
		private System.Nullable<bool> _Trangthaikhoa;
		
		private System.Nullable<System.DateTime> _Thoigianhethankhoa;
		
		private EntityRef<Nguoidung> _Nguoidung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDangnhapIDChanging(int value);
    partial void OnDangnhapIDChanged();
    partial void OnNguoidungIDChanging(System.Nullable<int> value);
    partial void OnNguoidungIDChanged();
    partial void OnSolandangnhapsaiChanging(System.Nullable<int> value);
    partial void OnSolandangnhapsaiChanged();
    partial void OnThoigiandangnhapChanging(System.Nullable<System.DateTime> value);
    partial void OnThoigiandangnhapChanged();
    partial void OnTrangthaikhoaChanging(System.Nullable<bool> value);
    partial void OnTrangthaikhoaChanged();
    partial void OnThoigianhethankhoaChanging(System.Nullable<System.DateTime> value);
    partial void OnThoigianhethankhoaChanged();
    #endregion
		
		public Dangnhap()
		{
			this._Nguoidung = default(EntityRef<Nguoidung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangnhapID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DangnhapID
		{
			get
			{
				return this._DangnhapID;
			}
			set
			{
				if ((this._DangnhapID != value))
				{
					this.OnDangnhapIDChanging(value);
					this.SendPropertyChanging();
					this._DangnhapID = value;
					this.SendPropertyChanged("DangnhapID");
					this.OnDangnhapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoidungID", DbType="Int")]
		public System.Nullable<int> NguoidungID
		{
			get
			{
				return this._NguoidungID;
			}
			set
			{
				if ((this._NguoidungID != value))
				{
					if (this._Nguoidung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoidungIDChanging(value);
					this.SendPropertyChanging();
					this._NguoidungID = value;
					this.SendPropertyChanged("NguoidungID");
					this.OnNguoidungIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solandangnhapsai", DbType="Int")]
		public System.Nullable<int> Solandangnhapsai
		{
			get
			{
				return this._Solandangnhapsai;
			}
			set
			{
				if ((this._Solandangnhapsai != value))
				{
					this.OnSolandangnhapsaiChanging(value);
					this.SendPropertyChanging();
					this._Solandangnhapsai = value;
					this.SendPropertyChanged("Solandangnhapsai");
					this.OnSolandangnhapsaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigiandangnhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> Thoigiandangnhap
		{
			get
			{
				return this._Thoigiandangnhap;
			}
			set
			{
				if ((this._Thoigiandangnhap != value))
				{
					this.OnThoigiandangnhapChanging(value);
					this.SendPropertyChanging();
					this._Thoigiandangnhap = value;
					this.SendPropertyChanged("Thoigiandangnhap");
					this.OnThoigiandangnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthaikhoa", DbType="Bit")]
		public System.Nullable<bool> Trangthaikhoa
		{
			get
			{
				return this._Trangthaikhoa;
			}
			set
			{
				if ((this._Trangthaikhoa != value))
				{
					this.OnTrangthaikhoaChanging(value);
					this.SendPropertyChanging();
					this._Trangthaikhoa = value;
					this.SendPropertyChanged("Trangthaikhoa");
					this.OnTrangthaikhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigianhethankhoa", DbType="DateTime")]
		public System.Nullable<System.DateTime> Thoigianhethankhoa
		{
			get
			{
				return this._Thoigianhethankhoa;
			}
			set
			{
				if ((this._Thoigianhethankhoa != value))
				{
					this.OnThoigianhethankhoaChanging(value);
					this.SendPropertyChanging();
					this._Thoigianhethankhoa = value;
					this.SendPropertyChanged("Thoigianhethankhoa");
					this.OnThoigianhethankhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nguoidung_Dangnhap", Storage="_Nguoidung", ThisKey="NguoidungID", OtherKey="NguoidungID", IsForeignKey=true)]
		public Nguoidung Nguoidung
		{
			get
			{
				return this._Nguoidung.Entity;
			}
			set
			{
				Nguoidung previousValue = this._Nguoidung.Entity;
				if (((previousValue != value) 
							|| (this._Nguoidung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nguoidung.Entity = null;
						previousValue.Dangnhaps.Remove(this);
					}
					this._Nguoidung.Entity = value;
					if ((value != null))
					{
						value.Dangnhaps.Add(this);
						this._NguoidungID = value.NguoidungID;
					}
					else
					{
						this._NguoidungID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Nguoidung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
