//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apgiatonghop
    {
        public int Id { get; set; }
        public Nullable<byte> CachTinh { get; set; }
        public Nullable<int> KhachhangID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<byte> IDLoaiApGia { get; set; }
        public Nullable<double> SanLuong { get; set; }
        public Nullable<int> ThangTongHop { get; set; }
        public Nullable<int> NamTongHop { get; set; }
    }
}
