//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backup
    {
        public int Id { get; set; }
        public string backup_filename { get; set; }
        public System.DateTime backup_date { get; set; }
        public Nullable<int> user_backup_id { get; set; }
    }
}
