//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietchisonuoctheotuyen
    {
        public int ChitietchisonuocID { get; set; }
        public Nullable<int> ChisonuocID { get; set; }
        public Nullable<int> KhachhangID { get; set; }
        public Nullable<System.DateTime> Ngaydocdongho { get; set; }
        public Nullable<System.DateTime> Ngaydoc { get; set; }
        public Nullable<int> Sodoc { get; set; }
        public string Sokhoan { get; set; }
    
        public virtual Chisonuoctheotuyen Chisonuoctheotuyen { get; set; }
        public virtual Khachhang Khachhang { get; set; }
    }
}
