//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Congno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Congno()
        {
            this.Chitietcongnoes = new HashSet<Chitietcongno>();
        }
    
        public int CongnoID { get; set; }
        public Nullable<int> KhachhangID { get; set; }
        public Nullable<int> NhanvienID { get; set; }
        public Nullable<System.DateTime> Ngayghinhan { get; set; }
        public Nullable<int> Tongcongno { get; set; }
        public Nullable<int> Congnoquahan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietcongno> Chitietcongnoes { get; set; }
        public virtual Khachhang Khachhang { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
    }
}
