//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dangnhap
    {
        public int DangnhapID { get; set; }
        public Nullable<int> NguoidungID { get; set; }
        public Nullable<int> Solandangnhapsai { get; set; }
        public Nullable<System.DateTime> Thoigiandangnhap { get; set; }
        public Nullable<bool> Trangthaikhoa { get; set; }
        public Nullable<System.DateTime> Thoigianhethankhoa { get; set; }
    
        public virtual Nguoidung Nguoidung { get; set; }
    }
}
