//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDich
    {
        public int GiaoDichID { get; set; }
        public Nullable<int> TienNopTheoThangID { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public Nullable<int> SoTien { get; set; }
        public Nullable<int> SoDu { get; set; }
    
        public virtual SoTienNopTheoThang SoTienNopTheoThang { get; set; }
    }
}
