//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadonnuocbihuy
    {
        public int Id { get; set; }
        public Nullable<int> HoadonnuocID { get; set; }
        public Nullable<System.DateTime> Ngayhuyhoadon { get; set; }
        public Nullable<int> Nguoihuyhoadon { get; set; }
        public string Lidohuyhoadon { get; set; }
        public string Nguoiyeucauhuy { get; set; }
        public string Sohieuhoadon { get; set; }
    }
}
