//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadonnuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoadonnuoc()
        {
            this.Chitiethoadonnuocs = new HashSet<Chitiethoadonnuoc>();
            this.SoTienNopTheoThangs = new HashSet<SoTienNopTheoThang>();
        }
    
        public int HoadonnuocID { get; set; }
        public Nullable<System.DateTime> Ngayhoadon { get; set; }
        public Nullable<int> KhachhangID { get; set; }
        public Nullable<int> NhanvienID { get; set; }
        public Nullable<int> Sohoadon { get; set; }
        public string Kyhieu { get; set; }
        public Nullable<int> SoKhoan { get; set; }
        public Nullable<int> Tongsotieuthu { get; set; }
        public Nullable<bool> Trangthaithu { get; set; }
        public Nullable<bool> Trangthaiin { get; set; }
        public Nullable<bool> Trangthaixoa { get; set; }
        public Nullable<bool> Trangthaichot { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> SoTienNopTheoThangID { get; set; }
        public Nullable<int> ThangHoaDon { get; set; }
        public Nullable<int> NamHoaDon { get; set; }
        public Nullable<System.DateTime> NgayNopTien { get; set; }
        public Nullable<System.DateTime> NgayIn { get; set; }
        public Nullable<System.DateTime> Ngaybatdausudung { get; set; }
        public Nullable<System.DateTime> Ngayketthucsudung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiethoadonnuoc> Chitiethoadonnuocs { get; set; }
        public virtual Khachhang Khachhang { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
        public virtual SoTienNopTheoThang SoTienNopTheoThang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoTienNopTheoThang> SoTienNopTheoThangs { get; set; }
    }
}
