//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HoaDonHaDongEntities : DbContext
    {
        public HoaDonHaDongEntities()
            : base("name=HoaDonHaDongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apgia> Apgias { get; set; }
        public virtual DbSet<ApGiaDacBiet> ApGiaDacBiets { get; set; }
        public virtual DbSet<Apgiatonghop> Apgiatonghops { get; set; }
        public virtual DbSet<Backup> Backups { get; set; }
        public virtual DbSet<Captuyen> Captuyens { get; set; }
        public virtual DbSet<Chinhanh> Chinhanhs { get; set; }
        public virtual DbSet<Chisocap> Chisocaps { get; set; }
        public virtual DbSet<Chisonuoctheotuyen> Chisonuoctheotuyens { get; set; }
        public virtual DbSet<Chitietchisonuoctheotuyen> Chitietchisonuoctheotuyens { get; set; }
        public virtual DbSet<Chitietcongno> Chitietcongnoes { get; set; }
        public virtual DbSet<Chitiethoadonnuoc> Chitiethoadonnuocs { get; set; }
        public virtual DbSet<Chucnangchuongtrinh> Chucnangchuongtrinhs { get; set; }
        public virtual DbSet<Chucvu> Chucvus { get; set; }
        public virtual DbSet<Congno> Congnoes { get; set; }
        public virtual DbSet<Cumdancu> Cumdancus { get; set; }
        public virtual DbSet<Dangnhap> Dangnhaps { get; set; }
        public virtual DbSet<Donghotong> Donghotongs { get; set; }
        public virtual DbSet<DuCo> DuCoes { get; set; }
        public virtual DbSet<GiaoDich> GiaoDiches { get; set; }
        public virtual DbSet<Hangsanxuat> Hangsanxuats { get; set; }
        public virtual DbSet<Hinhthucthanhtoan> Hinhthucthanhtoans { get; set; }
        public virtual DbSet<Hoadonnuoc> Hoadonnuocs { get; set; }
        public virtual DbSet<Hoadonnuocbihuy> Hoadonnuocbihuys { get; set; }
        public virtual DbSet<Khachhang> Khachhangs { get; set; }
        public virtual DbSet<Kiemdinh> Kiemdinhs { get; set; }
        public virtual DbSet<Lichsuhoadon> Lichsuhoadons { get; set; }
        public virtual DbSet<Lichsusudungct> Lichsusudungcts { get; set; }
        public virtual DbSet<Loaiapgia> Loaiapgias { get; set; }
        public virtual DbSet<Loaidongho> Loaidonghoes { get; set; }
        public virtual DbSet<LoaiKH> LoaiKHs { get; set; }
        public virtual DbSet<Nguoidung> Nguoidungs { get; set; }
        public virtual DbSet<Nhanvien> Nhanviens { get; set; }
        public virtual DbSet<Nhomchucnang> Nhomchucnangs { get; set; }
        public virtual DbSet<Phongban> Phongbans { get; set; }
        public virtual DbSet<Phuongxa> Phuongxas { get; set; }
        public virtual DbSet<Quanhuyen> Quanhuyens { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<Quyencuanguoidung> Quyencuanguoidungs { get; set; }
        public virtual DbSet<SoTienNopTheoThang> SoTienNopTheoThangs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Thongbao> Thongbaos { get; set; }
        public virtual DbSet<To> Toes { get; set; }
        public virtual DbSet<ToQuanHuyen> ToQuanHuyens { get; set; }
        public virtual DbSet<TuyenDuocChot> TuyenDuocChots { get; set; }
        public virtual DbSet<Tuyenkhachhang> Tuyenkhachhangs { get; set; }
        public virtual DbSet<Tuyenong> Tuyenongs { get; set; }
        public virtual DbSet<Tuyenongkythuat> Tuyenongkythuats { get; set; }
        public virtual DbSet<Tuyentheonhanvien> Tuyentheonhanviens { get; set; }
    }
}
