//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiemdinh
    {
        public int KiemdinhID { get; set; }
        public Nullable<int> KhachhangID { get; set; }
        public Nullable<System.DateTime> Ngaykiemdinh { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> Chisoluckiemdinh { get; set; }
        public Nullable<int> Chisosaukiemdinh { get; set; }
        public Nullable<int> HoaDonId { get; set; }
    }
}
