//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lichsuhoadon
    {
        public int ID { get; set; }
        public int HoaDonID { get; set; }
        public int ThangHoaDon { get; set; }
        public int NamHoaDon { get; set; }
        public string TenKH { get; set; }
        public string Diachi { get; set; }
        public string MST { get; set; }
        public string MaKH { get; set; }
        public string SoHopDong { get; set; }
        public int SanLuongTieuThu { get; set; }
        public int ChiSoCu { get; set; }
        public int ChiSoMoi { get; set; }
        public double SH1 { get; set; }
        public double SH1Price { get; set; }
        public double SH2 { get; set; }
        public double SH2Price { get; set; }
        public double SH3 { get; set; }
        public double SH3Price { get; set; }
        public double SH4 { get; set; }
        public double SH4Price { get; set; }
        public double HC { get; set; }
        public double HCPrice { get; set; }
        public double CC { get; set; }
        public double CCPrice { get; set; }
        public double SX { get; set; }
        public double SXPrice { get; set; }
        public double KD { get; set; }
        public double KDPrice { get; set; }
        public double ThueSuat { get; set; }
        public double ThueSuatPrice { get; set; }
        public double TileBVMT { get; set; }
        public double PhiBVMT { get; set; }
        public double TongCong { get; set; }
        public string BangChu { get; set; }
        public string TTVoOng { get; set; }
        public string TTThungan { get; set; }
        public int TuyenKHID { get; set; }
        public Nullable<int> TTDoc { get; set; }
        public double ChiSoCongDon { get; set; }
        public string NgayBatDau { get; set; }
        public string NgayKetThuc { get; set; }
    }
}
