//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoidung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nguoidung()
        {
            this.Dangnhaps = new HashSet<Dangnhap>();
            this.Lichsusudungcts = new HashSet<Lichsusudungct>();
            this.Quyencuanguoidungs = new HashSet<Quyencuanguoidung>();
            this.Thongbaos = new HashSet<Thongbao>();
        }
    
        public int NguoidungID { get; set; }
        public Nullable<int> NhanvienID { get; set; }
        public string Taikhoan { get; set; }
        public string Matkhau { get; set; }
        public Nullable<bool> Isadmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dangnhap> Dangnhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lichsusudungct> Lichsusudungcts { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quyencuanguoidung> Quyencuanguoidungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thongbao> Thongbaos { get; set; }
    }
}
