//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nhanvien()
        {
            this.Congnoes = new HashSet<Congno>();
            this.Hoadonnuocs = new HashSet<Hoadonnuoc>();
            this.Nguoidungs = new HashSet<Nguoidung>();
            this.Tuyentheonhanviens = new HashSet<Tuyentheonhanvien>();
        }
    
        public int NhanvienID { get; set; }
        public Nullable<int> PhongbanID { get; set; }
        public Nullable<int> ChucvuID { get; set; }
        public string Ten { get; set; }
        public string SDT { get; set; }
        public string Diachi { get; set; }
        public Nullable<int> ToQuanHuyenID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string MaNhanVien { get; set; }
    
        public virtual Chucvu Chucvu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Congno> Congnoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoadonnuoc> Hoadonnuocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nguoidung> Nguoidungs { get; set; }
        public virtual Phongban Phongban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tuyentheonhanvien> Tuyentheonhanviens { get; set; }
    }
}
