//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoTienNopTheoThang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoTienNopTheoThang()
        {
            this.DuCoes = new HashSet<DuCo>();
            this.GiaoDiches = new HashSet<GiaoDich>();
            this.Hoadonnuocs = new HashSet<Hoadonnuoc>();
        }
    
        public int ID { get; set; }
        public Nullable<int> HoaDonNuocID { get; set; }
        public Nullable<double> SoTienPhaiNop { get; set; }
        public Nullable<int> SoTienDaThu { get; set; }
        public int SoTienTrenHoaDon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuCo> DuCoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDich> GiaoDiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoadonnuoc> Hoadonnuocs { get; set; }
        public virtual Hoadonnuoc Hoadonnuoc { get; set; }
    }
}
