//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class To
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public To()
        {
            this.Tuyenkhachhangs = new HashSet<Tuyenkhachhang>();
        }
    
        public int ToID { get; set; }
        public Nullable<int> ChinhanhID { get; set; }
        public Nullable<int> PhuongxaID { get; set; }
        public string Ten { get; set; }
        public string Diachi { get; set; }
    
        public virtual Chinhanh Chinhanh { get; set; }
        public virtual Phuongxa Phuongxa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tuyenkhachhang> Tuyenkhachhangs { get; set; }
    }
}
