//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToQuanHuyen
    {
        public int ToQuanHuyenID { get; set; }
        public string Ma { get; set; }
        public Nullable<int> SoCN { get; set; }
        public Nullable<int> QuanHuyenID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> PhongbanID { get; set; }
    }
}
