//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuyenkhachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tuyenkhachhang()
        {
            this.Khachhangs = new HashSet<Khachhang>();
        }
    
        public int TuyenKHID { get; set; }
        public Nullable<int> ToID { get; set; }
        public Nullable<int> CumdancuID { get; set; }
        public string Ten { get; set; }
        public string Diachi { get; set; }
        public string Matuyen { get; set; }
        public Nullable<int> ChinhanhID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Cumdancu Cumdancu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Khachhang> Khachhangs { get; set; }
        public virtual To To { get; set; }
    }
}
