//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuyenong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tuyenong()
        {
            this.Donghotongs = new HashSet<Donghotong>();
            this.Tuyenong1 = new HashSet<Tuyenong>();
        }
    
        public int TuyenongID { get; set; }
        public Nullable<int> TuyenongPID { get; set; }
        public Nullable<int> CaptuyenID { get; set; }
        public string Matuyen { get; set; }
        public string Tentuyen { get; set; }
        public Nullable<int> QuanHuyenID { get; set; }
        public Nullable<int> PhuongxaID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> ChinhanhID { get; set; }
    
        public virtual Captuyen Captuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donghotong> Donghotongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tuyenong> Tuyenong1 { get; set; }
        public virtual Tuyenong Tuyenong2 { get; set; }
    }
}
