//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuyenDuocChot
    {
        public int ID { get; set; }
        public Nullable<int> TuyenKHID { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<bool> TrangThaiTinhTien { get; set; }
        public Nullable<bool> TrangThaiChot { get; set; }
        public Nullable<System.DateTime> NgayChot { get; set; }        
    }
}
