//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonNuocHaDong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuyentheonhanvien
    {
        public int ID { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public Nullable<int> TuyenKHID { get; set; }
    
        public virtual Nhanvien Nhanvien { get; set; }
    }
}
